version: '3'

services:
  grafana:
    container_name: menstagram_monitor_grafana
    image: grafana/grafana
    ports:
      - 3001:3000
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - prometheus
    networks:
      - menstagram

  prometheus:
    container_name: menstagram_monitor_prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - cadvisor
    networks:
      - menstagram

  cadvisor:
    container_name: menstagram_monitor_cadvisor
    image: google/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    environment:
      TZ: 'Asia/Tokyo'
    networks:
      - menstagram

networks:
  menstagram:
    external: true
