global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'menstagram-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - menstagram_monitor_prometheus:9090

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - menstagram_monitor_cadvisor:8080